name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Atualiza uma vez por dia
  workflow_dispatch: # Permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: fern-menezes
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo

          # MÃ³dulos extras
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_stars: yes
          plugin_stars_limit: 4

          # Onde salvar o arquivo
          filename: metrics.svg
